namespace Portal.Infrastructure.Storage;

public sealed record StoredFile(long SizeBytes, byte[] Sha256);

public sealed class FileTooLargeException(long maxBytes)
    : Exception($"The file is larger than the {maxBytes} byte limit.");

/// <summary>
/// Where uploaded bytes live. Keys are opaque and generated by the server; implementations must never let
/// a key escape their storage root.
/// </summary>
public interface IFileStorage
{
    /// <summary>
    /// Streams <paramref name="content"/> into storage, enforcing <paramref name="maxBytes"/> while reading
    /// (not after) and computing its SHA-256. Nothing is left behind on failure.
    /// </summary>
    /// <exception cref="FileTooLargeException">The content exceeded the limit.</exception>
    Task<StoredFile> SaveAsync(string key, Stream content, long maxBytes, CancellationToken ct);

    Task<Stream> OpenReadAsync(string key, CancellationToken ct);

    /// <summary>Removes the file if it exists. Deleting a missing file is not an error.</summary>
    Task DeleteAsync(string key, CancellationToken ct);
}
