namespace Portal.Domain;

public enum DeploymentStatus
{
    Queued = 1,
    Building = 2,
    Activating = 3,
    HealthChecking = 4,
    Succeeded = 5,
    Failed = 6,
    Cancelled = 7,
}

public enum DeploymentTrigger
{
    /// <summary>Built from the environment's branch (or a named ref).</summary>
    Manual = 1,

    /// <summary>Built again from the exact commit of an earlier deployment.</summary>
    Redeploy = 2,

    /// <summary>An earlier deployment's stored build made live again, without building.</summary>
    Rollback = 3,
}

/// <summary>Where and how one project is deployed (for example "staging" or "production").</summary>
public sealed class DeploymentEnvironment : Entity, ITenantScoped
{
    public Guid OrganizationId { get; set; }

    public Guid ProjectId { get; init; }

    public required string Name { get; set; }

    /// <summary>The DNS label the site is served under. Globally unique, generated by the server.</summary>
    public required string SiteLabel { get; init; }

    public required string RepositoryUrl { get; set; }

    public required string Branch { get; set; }

    public required string BuildCommand { get; set; }

    /// <summary>Folder, relative to the repository root, that the build produces.</summary>
    public required string OutputDirectory { get; set; }

    public required string HealthPath { get; set; }

    /// <summary>Serve <c>index.html</c> for unknown paths (single-page apps).</summary>
    public bool SpaFallback { get; set; }

    /// <summary>The Git access token, encrypted with ASP.NET Data Protection. Never returned by the API.</summary>
    public string? ProtectedAccessToken { get; set; }

    /// <summary>The deployment that is live right now, if any.</summary>
    public Guid? CurrentDeploymentId { get; set; }

    public DateTimeOffset CreatedAt { get; init; }

    public DateTimeOffset UpdatedAt { get; set; }
}

public sealed class Deployment : Entity, ITenantScoped
{
    public Guid OrganizationId { get; set; }

    public Guid ProjectId { get; init; }

    public Guid EnvironmentId { get; init; }

    public DeploymentStatus Status { get; set; } = DeploymentStatus.Queued;

    public DeploymentTrigger Trigger { get; init; }

    /// <summary>The branch, tag, or commit that was asked for.</summary>
    public required string Ref { get; init; }

    /// <summary>The commit that was actually built. Known once the source is fetched.</summary>
    public string? CommitSha { get; set; }

    /// <summary>The folder name of the stored build, once one exists.</summary>
    public string? ReleaseKey { get; set; }

    /// <summary>For a redeploy or rollback, the deployment it was based on.</summary>
    public Guid? SourceDeploymentId { get; init; }

    public Guid RequestedByUserId { get; init; }

    public DateTimeOffset CreatedAt { get; init; }

    public DateTimeOffset? StartedAt { get; set; }

    public DateTimeOffset? FinishedAt { get; set; }

    public string? FailureReason { get; set; }

    /// <summary>The new build failed its health check and the previous one was put back.</summary>
    public bool RevertedToPrevious { get; set; }

    public bool CancelRequested { get; set; }
}

public enum LogChannel
{
    System = 1,
    Stdout = 2,
    Stderr = 3,
}

/// <summary>One line of a deployment's log. Ordered by <see cref="Id"/>.</summary>
public sealed class DeploymentLogLine : ITenantScoped
{
    public long Id { get; init; }

    public Guid OrganizationId { get; set; }

    public Guid DeploymentId { get; init; }

    public DateTimeOffset At { get; init; }

    public LogChannel Channel { get; init; }

    public required string Message { get; init; }
}

public enum JobStatus
{
    Pending = 0,
    Running = 1,
    Succeeded = 2,
    Failed = 3,
}

/// <summary>
/// A unit of background work in the SQL-backed queue. Deliberately not tenant-scoped: the worker is a
/// system component and switches into the owning tenant for each job it runs.
/// </summary>
public sealed class BackgroundJob
{
    public Guid Id { get; init; } = Guid.CreateVersion7();

    public required string Type { get; init; }

    public Guid OrganizationId { get; init; }

    /// <summary>What the job is about (for a deployment job, the deployment id).</summary>
    public Guid EntityId { get; init; }

    public JobStatus Status { get; set; }

    public int Attempts { get; set; }

    public DateTimeOffset RunAfter { get; init; }

    public DateTimeOffset CreatedAt { get; init; }

    /// <summary>While running, the job belongs to <see cref="LockedBy"/> until this time; then it can be reclaimed.</summary>
    public DateTimeOffset? LeaseExpiresAt { get; set; }

    public string? LockedBy { get; set; }

    public DateTimeOffset? FinishedAt { get; set; }

    public string? Error { get; set; }
}
